spring.application.name=oracle-db-26ai-backend

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.data.jdbc.dialect=oracle

spring.sql.init.mode=always
spring.sql.init.separator=/
