-- Oracle Database 26ai. Statements use the configured Spring separator: /
-- DEMO RESET: drop and recreate both application tables on every startup.
-- Existing rows are removed. Drop the child table before its parent.

DROP TABLE IF EXISTS MAINTENANCE_REQUEST
/

DROP TABLE IF EXISTS ASSET
/

CREATE TABLE ASSET (
    ASSET_ID    VARCHAR2(50 CHAR)  NOT NULL,
    ASSET_NAME  VARCHAR2(200 CHAR) NOT NULL,
    ASSET_TYPE  VARCHAR2(30 CHAR)  NOT NULL,
    LOCATION    VARCHAR2(300 CHAR),
    MODEL       VARCHAR2(100 CHAR),
    CONSTRAINT PK_ASSET PRIMARY KEY (ASSET_ID),
    CONSTRAINT CK_ASSET_TYPE CHECK (
        ASSET_TYPE IN ('TRANSFORMER', 'POWERLINE', 'POLE', 'CIRCUIT_BREAKER', 'SUBSTATION')
    )
)
/

CREATE TABLE MAINTENANCE_REQUEST (
    REQUEST_ID       VARCHAR2(50 CHAR)  NOT NULL,
    ASSET_ID         VARCHAR2(50 CHAR)  NOT NULL,
    TITLE            VARCHAR2(300 CHAR) NOT NULL,
    STATUS           VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
    REPORTED_DATE    DATE NOT NULL,
    RESOLVED_DATE    DATE,
    PROBLEM          CLOB NOT NULL,
    FINDINGS         CLOB,
    SOLUTION_REMARKS CLOB,
    OUTCOME          CLOB,
    SEARCH_DOCUMENT  JSON,
    SEARCH_EMBEDDING VECTOR(*, FLOAT32),
    CONSTRAINT PK_MAINTENANCE_REQUEST PRIMARY KEY (REQUEST_ID),
    CONSTRAINT FK_MAINT_REQUEST_ASSET FOREIGN KEY (ASSET_ID)
        REFERENCES ASSET (ASSET_ID),
    CONSTRAINT CK_MAINT_REQUEST_STATUS CHECK (
        STATUS IN ('OPEN', 'IN_PROGRESS', 'RESOLVED')
    ),
    CONSTRAINT CK_MAINT_REQUEST_DATES CHECK (
        RESOLVED_DATE IS NULL OR RESOLVED_DATE >= REPORTED_DATE
    )
)
/

-- Keep the derived search document synchronized with the source fields.
CREATE OR REPLACE TRIGGER TRG_MAINTENANCE_SEARCH_DOC
BEFORE INSERT OR UPDATE ON MAINTENANCE_REQUEST
FOR EACH ROW
BEGIN
    SELECT JSON_OBJECT(
        'title'           VALUE :NEW.TITLE,
        'problem'         VALUE :NEW.PROBLEM,
        'findings'        VALUE :NEW.FINDINGS,
        'solutionRemarks' VALUE :NEW.SOLUTION_REMARKS,
        'outcome'         VALUE :NEW.OUTCOME
        ABSENT ON NULL
        RETURNING JSON
    )
    INTO :NEW.SEARCH_DOCUMENT
    FROM DUAL;

END;
/

-- The schema owner needs a direct SELECT grant on this mining model.
-- FOLLOWS ensures the JSON document is rebuilt before it is embedded.
-- The model determines vector dimensions. Long documents need a chunking strategy
-- that respects the embedding model input limit.
CREATE OR REPLACE TRIGGER TRG_MAINTENANCE_SEARCH_EMBED
BEFORE INSERT OR UPDATE ON MAINTENANCE_REQUEST
FOR EACH ROW
FOLLOWS TRG_MAINTENANCE_SEARCH_DOC
BEGIN
    SELECT VECTOR_EMBEDDING(
        PDB1_ADMIN.ALL_MINILM_L12_V2
        USING JSON_SERIALIZE(:NEW.SEARCH_DOCUMENT RETURNING CLOB ERROR ON ERROR) AS DATA
    )
    INTO :NEW.SEARCH_EMBEDDING
    FROM DUAL;
END;
/
